(in-package :mlsspbc.resources)

(defpage-no-redirect sign-up ()
  `(:div :id "reg"
	 (:form :action ,(append-root-url "/register-process") :method "post" :class "register"
		(:h1 :style "float:left" "Account Registration")
		(:div :style "text-align: right;margin-top:5px;margin-right:10px;"
				 (:a :href ,(append-root-url "/") "TOPへ戻る"))
		(:fieldset :class "row1"
			   (:legend "Account Details")
			   (:div :style "text-align:center;font-size:2.5em;color:red;"
				 ,(let ((input-error (get-parameter "er")))
				    (format nil "~A"
					    (cond ((null input-error) "")
						  ((string= input-error "v-mail") "Invalid email address")
						  ((string= input-error "e-mail") "Email address is empty")
						  ((string= input-error "d-mail") "Email-address is already registered")
						  ((string= input-error "v-password") "Invalid password")
						  ((string= input-error "e-password") "Password is empty")
						  ((string= input-error "e-name") "Name is empty")
						  ((string= input-error "e-year") "Yout birth year is empty")
						  (t "")))))
			   (:div :style "text-align:center;color:red;" "※メールアドレスとパスワードは本システムのログインの際に使うので覚えておいてください")
			   (:p)
			   (:label "Email *")
			   (:input :type "text" :name "email" :class "mail" :size "" :placeholder " Email: sample@hogehoge.com" :autofocus)
			   (:p)
			   (:label "Password*")
			   (:input :type "password" :name "password1" :value "password1" :placeholder " Password")
			   (:label "Repeat Password*")
			   (:input :type "password" :name "password2" :value "password2" :placeholder " Same Password"))
		(:fieldset :class "row2"
			   (:legend "Personal Details")
			   (:p)
			   (:label "Name *")
			   (:input :type "text" :class "long" :name "username" :placeholder " Your Name")
			   (:p)
			   (:label "Country *")
			   (:select :name "nationality"
			    (:option :value "Japan" "Japan")
			    (:option :value "US" "United State")
			    (:option :value "China" "China")
			    (:option :value "France" "France")))
		(:fieldset :class "row3"
			   (:legend "Further Information")
			   (:p)
			   (:label "Gender *")
			   (:input :type "radio" :name "gender" :value "male" :id "gender-male-radio")
			   (:label :class "gender" :for "gender-male-radio" "Male")
			   (:input :type "radio" :name "gender" :value "female" :id "gender-female-radio")
			   (:label :class "gender" :for "gender-female-radio" "Female")
			   (:input :type "radio" :name "gender" :value "none" :id "gender-less-radio" :checked "checked")
			   (:label :class "gender" :for "gender-less-radio" "None")
			   (:p)
			   (:label "Birthday *")
			   (:select :class "date" :name "birth_day"
				    (:option :value "1" "01")
				    (:option :value "2" "02")
				    (:option :value "3" "03")
				    (:option :value "4" "04")
				    (:option :value "5" "05")
				    (:option :value "6" "06")
				    (:option :value "7" "07")
				    (:option :value "8" "08")
				    (:option :value "9" "09")
				    (:option :value "10" "10")
				    (:option :value "11" "11")
				    (:option :value "12" "12")
				    (:option :value "13" "13")
				    (:option :value "14" "14")
				    (:option :value "15" "15")
				    (:option :value "16" "16")
				    (:option :value "17" "17")
				    (:option :value "18" "18")
				    (:option :value "19" "19")
				    (:option :value "20" "20")
				    (:option :value "21" "21")
				    (:option :value "22" "22")
				    (:option :value "23" "23")
				    (:option :value "24" "24")
				    (:option :value "25" "25")
				    (:option :value "26" "26")
				    (:option :value "27" "27")
				    (:option :value "28" "28")
				    (:option :value "29" "29")
				    (:option :value "30" "30")
				    (:option :value "31" "31"))
			   (:select :name "birth_month"
			    (:option :value "1" "January")
			    (:option :value "2" "February")
			    (:option :value "3" "March")
			    (:option :value "4" "April")
			    (:option :value "5" "May")
			    (:option :value "6" "June")
			    (:option :value "7" "July")
			    (:option :value "8" "August")
			    (:option :value "9" "September")
			    (:option :value "10" "October")
			    (:option :value "11" "November")
			    (:option :value "12" "December" ""))
			   (:input :class "year" :name "birth_year" :type "text" :size "4" :maxlength "4" :placeholder "e.g 1976")
			   (:p)
			   (:label "User Type * ")
			   (:input :type "radio" :name "user_type" :value "learner" :id "user-type-learner" :checked "checked")
			   (:label :class "utype" :for "user-type-learner" "Learner")
			   (:input :type "radio" :name "user_type" :value "teacher" :id "user-type-teacher")
			   (:label :class "utype" :for "user-type-teacher" "Teacher")
			   (:button :type "submit" :id "register-btn" :class "button" :style "clear:both;" "Register &raquo;")
			   (:p)
			   ;; (:div :style "text-align:right;"
			   ;; 	 (:a :href "/static/terms/terms-of-service-ja.html" "利用規約（日本語）")
			   ;; 	 (:br)
			   ;; 	 (:a :href "/static/terms/terms-of-service-en.html" "Terms of services"))
			   ))
	 (:p)
	 (:div :style "background-color:white;border:1px solid black;width:700px;margin-right:auto;margin-left:auto;overflow:scroll;"
	       (:iframe :src ,(append-root-url "/static/terms/terms-of-service-ja.html") :width "700px" :height "300px"))))
